### PR TITLE
feat: 🎸 cancel ci runs that are currently running on push

### PR DESCRIPTION
**Pull request by maniator**
See docs here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency

Prevents multiple runs of a branch running at the same time

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by adebayor123** [comment]
Hi maniator@, in the description of the PR, would you be able to provide the following details to provide more context?

1. What is the problem (What was the previous behavior without this change)?
2. What does this change do (What is the expected/changed behavior)?
3. What is the gain from this change?

I believe the purpose of this PR is to tag pending/running workflows by their branch, and whenever a contributor triggers another workflow in the same branch, the currently running and pending workflows are cancelled, and the newly triggered workflow will run instead. Is this correct?

Thank you, and we greatly appreciate your contributions!

**Comment by maniator** [comment]
> Hi maniator@, in the description of the PR, would you be able to provide the following details to provide more context?
> 
>     1. What is the problem (What was the previous behavior without this change)?
> 
>     2. What does this change do (What is the expected/changed behavior)?
> 
>     3. What is the gain from this change?
> 
> 
> I believe the purpose of this PR is to tag pending/running workflows by their branch, and whenever a contributor triggers another workflow in the same branch, the currently running and pending workflows are cancelled, and the newly triggered workflow will run instead. Is this correct?

Yup that is the idea 💡

> 
> Thank you, and we greatly appreciate your contributions!

**Comment by adebayor123** [comment]
Hi maniator@, when I am trying to test out the change on my fork, I am facing an error: https://github.com/adebayor123/aws-rum-web/actions/runs/2308985289.

Pulling your repository and even manual edit leads to the same result.

**Comment by maniator** [comment]
> Hi maniator@, when I am trying to test out the change on my fork, I am facing an error: https://github.com/adebayor123/aws-rum-web/actions/runs/2308985289.
> 
> Pulling your repository and even manual edit leads to the same result.

Weird

I followed some docs.

I will look in my fork

**Comment by maniator** [comment]
@adebayor123 Fixed it!

Here is a cancelled workflow due to new changes (on my fork): https://github.com/maniator/aws-rum-web/actions/runs/2319984558
And here is the one that superseded it: https://github.com/maniator/aws-rum-web/actions/runs/2319987514

**Comment by maniator** [comment]
can see example on this main fork here

Cancelled action: https://github.com/aws-observability/aws-rum-web/actions/runs/2320049866

New action: https://github.com/aws-observability/aws-rum-web/actions/runs/2320060455

**Comment by adebayor123** [comment]
The change works now! :-)

**Review by adebayor123 — APPROVED** [review]

**Pull request merged**
